---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: ./test.sh
      - name: Check login
        if: runner.os != 'macos'
        run: ./wait_for_login.sh
      - name: Check OMERO.web
        run: ./check_web.sh
      - name: Check logs
        run: docker-compose logs
        if: ${{ failure() }}
