---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup docker
        if: runner.os == 'macos'
        run: |
          brew install docker
          brew install docker-compose
      - name: Symlink (compose is now a cli-plugins)
        if: runner.os == 'macos'
        run: |
          mkdir -p ~/.docker/cli-plugins
          ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
      - name: Start docker
        if: runner.os == 'macos'
        run: colima start 
      - name: Test
        run: ./test.sh
      - name: Check login
        run: ./wait_for_login.sh
      - name: Check OMERO.web
        run: ./check_web.sh
      - name: Check logs
        run: docker compose logs
        if: ${{ failure() }}
